### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by uniqname**
Added tests, which illuminated the need for some rewrites.
Will require a major version bump.

### CODE REVIEW

**Comment by tuxsudo** [comment]
The README doc is out of date.

**Comment by tuxsudo** [comment]
Looks awesome. My only feedback would be to provide more examples to show off its power...

**Comment by uniqname** [comment]
@tuxsudo Changed demo. Take a look and tell me what you think.

**Comment by tuxsudo** [comment]
:+1:

**Pull request merged**
